Downgrade JS
dcos-labs/recordio pull request #2
Opened 2017-11-15 14:23 UTC by nLight

Usage of `let` causes trouble with `webpack@1` `uglifyjs` plugin.

2017-11-15 15:28 UTC, Poltergeist requested changes
As `var` has a different scope then `let` and `const` I would advise to change the way the variables are defined, I would opt to define all the variables at the top of their scope which would be the function. Just to omit the possibility that one variable could be defined multiple times and because the `var` declaration is hoisted anyway so we are not changing anything code execution wise if we place all the `var`s at the beginning of the scope. It makes this only more visible.

2017-11-15 15:35 UTC, nLight commented
@Poltergeist totally 👍  please have another look

2017-11-16 08:51 UTC, juliangieseke approved these changes

2017-11-16 10:40 UTC, orlandohohmeier approved these changes

2017-11-16 11:24 UTC, Poltergeist approved these changes
👍 Let's get this merged.

2017-11-16 11:24 UTC, Poltergeist commented on src/read.js
> +    record;
👍 This is what meant.

2017-11-16 11:24 UTC, merged